### ISSUE TITLE
North out of memory

### ISSUE THREAD

**Issue by DerOliDE** [BakermanLP/ProjectRET-AoT#128]
Crash-Report: https://gist.github.com/DerOli82/153bdfa4655002016fd8270d700b52f9

Und der Server bleibt nach dem Crash mit einer weiteren out of memory exception hängen:
```
[08:16:00] [Server thread/ERROR]: This crash report has been saved to: /home/north/./crash-reports/crash-2017-10-14_08.15.52-server.txt
[08:16:00] [Server thread/INFO]: Stopping server
[08:16:00] [Server thread/ERROR]: Exception stopping the server
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:745) ~[minecraft_server.1.11.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:322) ~[minecraft_server.1.11.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:728) ~[minecraft_server.1.11.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:884) ~[minecraft_server.1.11.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:555) ~[minecraft_server.1.11.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:419) ~[minecraft_server.1.11.2.jar:?]
        at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:828) ~[minecraft_server.1.11.2.jar:?]
        at io.netty.channel.AbstractChannel.close(AbstractChannel.java:178) ~[minecraft_server.1.11.2.jar:?]
        at net.minecraft.network.NetworkSystem.func_151268_b(NetworkSystem.java:155) ~[mh.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:382) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:535) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[08:18:42] [Server thread/INFO]: [STDERR]: java.lang.OutOfMemoryError: Java heap space

```

**Comment by DerOliDE** [comment]
Server hat sich wieder aufgehängt mit out of memory. Ich habe North jetzt mal testweise 6GB zugewiesen und @BakermanLP kannst Du mal dafür sorgen das South kein täglichen neustart macht, damit er ausbleibt. Ich möchte hier ausschließen das irgendeine Mod oder irgendein Plugin ein Memory Leak verursacht, da 4GB für die geringe Anzahl an Testern ja eigentlich ausreichend sein sollten.

Log: https://gist.github.com/DerOli82/c5a0fca5e1fcd69e3e9358a31431ef91

**Comment by DerOliDE** [comment]
Ich schließe das hier mal, da das Problem nicht mehr aufgetreten ist.
