### ISSUE TITLE
[1.12.2]Game Crash bei Start

### ISSUE THREAD

**Issue by Ghost-Gamer** [BakermanLP/ProjectRET-AoT#262]
Game Crasht direkt nach Starten mit Meldung:
```
"The game is running. Please wait.
2018-06-19 17:05:44,950 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[17:05:45] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:05:45] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_66]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Process ended with code: 1"
```
-Neuinstallation mehrfach erfolglos.

**Comment by DerOliDE** [comment]
Aus irgendeinem Grund wurde Forge nicht korrekt installiert.

Wurde die komplette Instanz mit "Delete files" gelöscht? "Hard force update" löscht nämlich nicht alles.
Wenn das nicht hilft auch mal die Libraries löschen, damit Forge neu runtergeladen wird. Ich kann Dir aber leider nicht sagen, wo die unter Windows liegen, bei mir sieht der Inhalt des Verzeichnisses folgendermaßen aus:
```
accounts.dat
assets/
config.json/
httpcore-nio-4.3.jar.zip
instances/
launcher/
libraries/ <<<<<< **Den Ordner löschen**
ProjectRET-Launcher.jar 
temp/
versions/
```

**Comment by Ghost-Gamer** [comment]
Ok thanks, das löschen der libraries hat es getan

**Comment by BakermanLP** [comment]
Da es jetzt funktioniert ... Close
